name = "distracted-drivers-keras"
repo = "<CLONE URL GOES HERE>"
description = "State Farm Distracted Driver Challenge"
environment = "tensorflow"

[datasets]
"<USERNAME GOES HERE>/distracted-drivers-keras" = "0.0.2"
