name = "distracted-drivers"
repo = "<CLONE URL GOES HERE>"
description = "State Farm Distracted Driver Challenge"
environment = "tensorflow"

[datasets]
"<USERNAME GOES HERE>/distracted-drivers" = "0.0.2"
